from affin import decrypt, valid_keys
from break_caesar import chi_squared, LETTER_FREQUENCIES

def break_affine(ciphertext: str, language: str = "en") -> tuple[tuple[int, int], str]:
    """
    Breaks an Affine cipher by testing all 312 valid (a, b) key combinations and 
    returning the key pair and plaintext that minimize the Chi-Squared statistic.
    """
    # Step A: Validate language selection and retrieve frequency table
    if language not in LETTER_FREQUENCIES:
        raise ValueError(f"Unsupported language code '{language}'. Use 'en' or 'es'.")

    table = LETTER_FREQUENCIES[language]

    # Step B: Initialize tracking variables for the minimum score search
    best_key = (1, 0)
    lowest_score = float("inf")
    best_plaintext = ""

    # Step C: Evaluate all 312 valid key pairs (a, b) generated by valid_keys()
    for a, b in valid_keys():
        candidate_text = decrypt(ciphertext, a, b)
        score = chi_squared(candidate_text, table)

        # Step D: Keep track of the key pair that produces the lowest (best) score
        if score < lowest_score:
            lowest_score = score
            best_key = (a, b)
            best_plaintext = candidate_text

    # Step E: Return best key pair tuple ((a, b), plaintext)
    return best_key, best_plaintext
